services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.timescale
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    command:
      [
        "postgres",
        "-c",
        "log_destination=stderr",
        "-c",
        "log_line_prefix=%m [%p] ",
        "-c",
        "log_statement=all",
        "-c",
        "log_min_duration_statement=0",
      ]
    volumes:
      - pgdata:/home/postgres/pgdata

volumes:
  pgdata:
